version: '3.1'

services:

  postgis:
    image: postgis/postgis:13-3.1-alpine
    restart: always
    environment:
      # ToDo: this might be a security issue,
      # does not allow connection otherwise atm
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: datentool
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    env_file: .env
    build: .
    image: datentool
    links:
      - postgis:db
    command: bash -c "cd /root/datentool && git pull && pip install -r requirements.txt && cd angular-frontend && npm ci && ng build --stats_json --build-optimizer && cd /root/datentool && python manage.py migrate --run-syncdb && python manage.py loaddata users && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "${EXT_PORT}:8000"
    restart: unless-stopped
    volumes:
      - ./public:/root/datentool/public

volumes:
  postgres_data: